language: node_js
node_js:
 - "node"

cache: npm

script: npm run build
branches:
  only:
    - master
    - production
deploy:
  provider: heroku
  api_key:
    secure: $API_KEY
  app: viewjs-paw
  on: production
